version: '3'
services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/moviesdb
      REDIS_URI: redis://redis:6379
      ENABLE_WRITING_HANDLERS: 'false'
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:8.0-rc
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: moviesdb

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/moviesdb
    depends_on:
      - mongo

networks:
  backend:
    driver: bridge
