version: '3'
services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017
      REDIS_URI: redis://redis:6379
      ENABLE_WRITING_HANDLERS: 'false'
    depends_on:
      - mongo
      - redis
    networks:
      - backend-api
      - backend-db

  mongo:
    image: mongo:8.0-rc
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - backend-db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend-api

networks:
  backend-api:
    driver: bridge
  backend-db:
    driver: bridge
